# become is required when logging in as ubuntu ie. default aws servers
- name: Create/Remove User 
  become: yes
  user: name={{ item.key }} shell=/bin/bash groups={{ item.value.groups }} state={{ item.value.state }} remove=yes update_password=always password={{master_users_list['users'][item.key].password}} force=yes
  with_dict: users

- name : Check ~/.ssh directory exists
  become: yes
  file: path=/home/{{ item.key }}/ group={{ item.key }} owner={{ item.key }} state=directory mode=755
  with_dict: users
  when: item.value.state == 'present'

- name : Check ~/.ssh directory exists
  become: yes
  file: path=/home/{{ item.key }}/.ssh group={{ item.key }} owner={{ item.key }} state=directory mode=700
  with_dict: users
  when: item.value.state == 'present'

- name: Replace Authorized_keys with templated version
  template: src=authorized_keys.j2 dest=/home/{{ item.key }}/.ssh/authorized_keys owner={{ item.key }} group={{ item.key }} mode=644 backup=yes
  become: yes
  with_dict:  users
  when: item.value.state == 'present' 

